# Generated by Django 6.0.3 on 2026-04-11 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_is_seller_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_seller',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_seller_pending',
        ),
    ]
