# Generated by Django 6.0.3 on 2026-04-11 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_shippingconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
