# Generated by Django 6.0.3 on 2026-04-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override price for this variation', max_digits=10, null=True),
        ),
    ]
