# Generated by Django 6.0.3 on 2026-04-11 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productvariation_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Quantity', 'verbose_name_plural': 'Quantities'},
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='store.size', verbose_name='Quantities'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.size', verbose_name='Quantity'),
        ),
    ]
