# Generated by Django 6.0.5 on 2026-05-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_sitesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
