# Generated by Django 6.0.3 on 2026-04-11 01:38

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0009_remove_product_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSalesReport',
            fields=[
            ],
            options={
                'verbose_name': 'Overall Sale',
                'verbose_name_plural': 'Overall Sales Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.order',),
        ),
        migrations.CreateModel(
            name='ProductSalesReport',
            fields=[
            ],
            options={
                'verbose_name': 'Product Sale',
                'verbose_name_plural': 'Product Sales Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.product',),
        ),
    ]
